/* Conciliador CIA-ERPCO. Todo se procesa localmente en el navegador. */
pdfjsLib.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.worker.min.js';
const $=s=>document.querySelector(s), money=n=>new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN'}).format(Number(n||0));
const state={files:[],result:null};
const TYPES=[['cia','CIA cierre'],['erpcoSur','ERPCO SUR'],['erpcoSurVb','ERPCO SUR Volksbus'],['erpcoTrt','ERPCO TRT'],['erpcoTrtVb','ERPCO TRT Volksbus'],['avaSur','AVA SUR'],['avaTrt','AVA TRT'],['depCia','Depósitos CIA'],['depErpco','Depósitos ERPCO']];
$('#fecha').value=new Date().toISOString().slice(0,10);
function addFicha(nombre='',importe=''){const row=document.createElement('div');row.className='ficha-row';row.innerHTML=`<input class="ficha-nombre" placeholder="FICHA" value="${nombre}"><input class="ficha-importe" type="number" step="0.01" placeholder="0.00" value="${importe}"><button class="remove" title="Eliminar">×</button>`;row.querySelector('.remove').onclick=()=>row.remove();$('#fichas').append(row)}
addFicha('ING DEPOSITO EN CAMINO','');addFicha('DEPÓSITO ANTICIPADO','0');addFicha('VHT','');addFicha('CRT','');
$('#addFicha').onclick=()=>addFicha();$('#demoBtn').onclick=()=>{state.files=[];state.result=null;$('#files').value='';renderFiles();$('#summary').classList.add('hidden');$('#actions').classList.add('hidden');setStatus('Carga los archivos y presiona “Procesar conciliación”.','muted')};
const dz=$('#dropZone');['dragenter','dragover'].forEach(e=>dz.addEventListener(e,x=>{x.preventDefault();dz.classList.add('drag')}));['dragleave','drop'].forEach(e=>dz.addEventListener(e,x=>{x.preventDefault();dz.classList.remove('drag')}));dz.addEventListener('drop',e=>loadFiles(e.dataTransfer.files));$('#files').onchange=e=>loadFiles(e.target.files);
function loadFiles(list){state.files=[...state.files,...Array.from(list)].filter((f,i,a)=>a.findIndex(x=>x.name===f.name&&x.size===f.size)===i);renderFiles()}
function renderFiles(){const g=$('#fileGrid');g.innerHTML='';state.files.forEach(f=>{const d=document.createElement('div');d.className='file-item';d.innerHTML=`<i class="dot"></i><div><b>${detectType(f.name)?.label||'Archivo adicional'}</b><small>${f.name}</small></div>`;g.append(d)})}
function detectType(name){const n=name.toUpperCase().replace(/\s+/g,' ');let key=null;if(n.includes('DEPOSITO')&&n.includes('ERPCO'))key='depErpco';else if(n.includes('DEPOSITO')&&n.includes('CIA'))key='depCia';else if(n.includes('AVA')&&n.includes('SUR'))key='avaSur';else if(n.includes('AVA')&&n.includes('TRT'))key='avaTrt';else if(n.includes('ERPCO')&&n.includes('SUR')&&(n.includes('VB')||n.includes('VOLK')))key='erpcoSurVb';else if(n.includes('ERPCO')&&n.includes('TRT')&&(n.includes('VB')||n.includes('VOLK')))key='erpcoTrtVb';else if(n.includes('ERPCO')&&n.includes('SUR'))key='erpcoSur';else if(n.includes('ERPCO')&&n.includes('TRT'))key='erpcoTrt';else if(n.includes('CIA'))key='cia';return key?{key,label:TYPES.find(x=>x[0]===key)[1]}:null}
const num=v=>{if(typeof v==='number')return v;let s=String(v??'').replace(/\s/g,'').replace(/\$/g,'').replace(/,/g,'').replace(/^\.(\d)/,'0.$1').replace(/^\-\./,'-0.');const x=parseFloat(s);return Number.isFinite(x)?x:0};
function parseCSV(text){const out=[];let row=[],cell='',q=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(c==='"'&&q&&n==='"'){cell+='"';i++}else if(c==='"')q=!q;else if(c===','&&!q){row.push(cell);cell=''}else if((c==='\n'||c==='\r')&&!q){if(c==='\r'&&n==='\n')i++;row.push(cell);if(row.some(x=>x!==''))out.push(row);row=[];cell=''}else cell+=c}if(cell||row.length){row.push(cell);out.push(row)}return out}
function brandName(s){s=String(s).toUpperCase().replace(/\s+/g,' ');if(s.includes('SUR')&&s.includes('VOLK'))return 'SUR VOLKSBUS';if(s.includes('TRT')&&s.includes('VOLK'))return 'TRT VOLKSBUS';if(s.trim()==='SUR'||s.startsWith('SUR '))return 'SUR';if(s.trim()==='TRT'||s.startsWith('TRT '))return 'TRT';return null}
async function textOf(f){return new TextDecoder('utf-8').decode(await f.arrayBuffer())}
async function parseCIA(f){const html=await textOf(f),doc=new DOMParser().parseFromString(html,'text/html');const tables=[...doc.querySelectorAll('table')];let rows=[];for(const t of tables){const r=[...t.rows].map(x=>[...x.cells].map(c=>c.textContent.trim().replace(/\s+/g,' ')));if(r.some(x=>x.some(c=>c.includes('Dif. Canje')))&&r.some(x=>x[0]?.toUpperCase().includes('SUR')))rows=r}
const summary={},drivers=new Map();let headers=null;for(const r of rows){if(r.some(c=>c==='Venta Canje'||c==='Venta canje:')){headers=r.map(c=>c.replace(/:$/,''));continue}const b=brandName(r[0]);if(b&&r.length>20){summary[b]={canje:num(r[5]),efectivo:num(r[11]),prepago:num(r[17]),difCanje:num(r[9])};continue}if(headers&&/^N$/i.test(r[0]||'')&&/^\d{6,}$/.test(r[3]||'')){const id=r[3];const cur=drivers.get(id)||{id,nombre:'',cia:{canje:0,efectivo:0,prepago:0},erpco:{canje:0,efectivo:0,prepago:0},marcas:new Set()};cur.cia.canje+=num(r[6]);cur.cia.efectivo+=num(r[12]);cur.cia.prepago+=num(r[18]);drivers.set(id,cur)}}
const date=(html.match(/Periodo Correspondiente del[\s\S]{0,300}?(\d{2}\/\d{2}\/\d{4})/i)||[])[1]||'';return{summary,drivers,date}}
function parseErpcoStandard(text,brand){const rows=parseCSV(text),drivers=new Map(),tot={canje:0,efectivo:0,prepago:0};for(const r of rows){if(!/^\d{6,}$/.test((r[0]||'').trim())||r.length<10)continue;const id=r[0].trim(),canje=num(r[7]),efectivo=num(r[8]),prepago=num(r[6]);tot.canje+=canje;tot.efectivo+=efectivo;tot.prepago+=prepago;const d=drivers.get(id)||{id,nombre:'',erpco:{canje:0,efectivo:0,prepago:0},marcas:new Set()};d.erpco.canje+=canje;d.erpco.efectivo+=efectivo;d.erpco.prepago+=prepago;d.marcas.add(brand);drivers.set(id,d)}return{tot,drivers}}
function parseErpcoVB(text,brand){const rows=parseCSV(text),drivers=new Map(),tot={canje:0,efectivo:0,prepago:0};for(const r of rows){if(r.length<18||!/^\d{6,}$/.test((r[10]||'').trim()))continue;const id=r[10].trim(),prepago=num(r[4]),canje=num(r[5]),efectivo=num(r[6]);tot.canje+=canje;tot.efectivo+=efectivo;tot.prepago+=prepago;const d=drivers.get(id)||{id,nombre:'',erpco:{canje:0,efectivo:0,prepago:0},marcas:new Set()};d.erpco.canje+=canje;d.erpco.efectivo+=efectivo;d.erpco.prepago+=prepago;d.marcas.add(brand);drivers.set(id,d)}return{tot,drivers}}
async function parseAVA(f){const wb=XLSX.read(await f.arrayBuffer(),{type:'array'}),ws=wb.Sheets[wb.SheetNames[0]],rows=XLSX.utils.sheet_to_json(ws,{defval:''});let total=0;for(const r of rows){const k=Object.keys(r).find(x=>x.toLowerCase().includes('monto recuperado'));total+=num(r[k])}return total}
async function parseDepCIA(f){const txt=await textOf(f);const m=txt.match(/TOTAL[\s\S]{0,250}?\$\s*([\d,]+\.\d{2})/i);if(m)return num(m[1]);const all=[...txt.matchAll(/\$\s*([\d,]+\.\d{2})/g)].map(x=>num(x[1]));return Math.max(0,...all)}
async function parsePDF(f){const pdf=await pdfjsLib.getDocument({data:await f.arrayBuffer()}).promise;let text='';for(let p=1;p<=pdf.numPages;p++){const page=await pdf.getPage(p),c=await page.getTextContent();text+=c.items.map(x=>x.str).join(' ')+'\n'}const m=text.match(/T\s*O\s*T\s*A\s*L\s*:?\s*\$?\s*([\d,]+\.\d{2})/i);if(m)return num(m[1]);const vals=[...text.matchAll(/\$\s*([\d,]+\.\d{2})/g)].map(x=>num(x[1]));return Math.max(0,...vals)}
function mergeDriver(target,map){for(const [id,d] of map){const x=target.get(id)||{id,nombre:'',cia:{canje:0,efectivo:0,prepago:0},erpco:{canje:0,efectivo:0,prepago:0},marcas:new Set()};if(d.cia)for(const k of ['canje','efectivo','prepago'])x.cia[k]+=d.cia[k]||0;if(d.erpco)for(const k of ['canje','efectivo','prepago'])x.erpco[k]+=d.erpco[k]||0;for(const b of d.marcas||[])x.marcas.add(b);target.set(id,x)}}
function setStatus(msg,kind='muted'){const s=$('#status');s.className='status '+kind;s.textContent=msg}
$('#procesar').onclick=async()=>{try{setStatus('Procesando archivos…');const found={};for(const f of state.files){const t=detectType(f.name);if(t)found[t.key]=f}const required=['cia','erpcoSur','erpcoSurVb','erpcoTrt','erpcoTrtVb'];const missing=required.filter(k=>!found[k]);if(missing.length)throw new Error('Faltan archivos indispensables: '+missing.map(k=>TYPES.find(x=>x[0]===k)[1]).join(', '));
const cia=await parseCIA(found.cia);if(Object.keys(cia.summary).length<4)throw new Error('No se pudo localizar el resumen por marca dentro del reporte CIA.');const drivers=new Map();mergeDriver(drivers,cia.drivers);const erpco={};for(const [key,brand,vb] of [['erpcoSur','SUR',false],['erpcoSurVb','SUR VOLKSBUS',true],['erpcoTrt','TRT',false],['erpcoTrtVb','TRT VOLKSBUS',true]]){const p=vb?parseErpcoVB(await textOf(found[key]),brand):parseErpcoStandard(await textOf(found[key]),brand);erpco[brand]=p.tot;mergeDriver(drivers,p.drivers)}
const avaSur=found.avaSur?await parseAVA(found.avaSur):0,avaTrt=found.avaTrt?await parseAVA(found.avaTrt):0,depCia=found.depCia?await parseDepCIA(found.depCia):0,depErpco=found.depErpco?await parsePDF(found.depErpco):0;
const diffs=[...drivers.values()].map(d=>{const ciaT=d.cia.canje+d.cia.efectivo+d.cia.prepago,erpT=d.erpco.canje+d.erpco.efectivo+d.erpco.prepago;return{id:d.id,nombre:d.nombre,marca:[...d.marcas].join(', '),ciaCanje:d.cia.canje,erpcoCanje:d.erpco.canje,difCanje:d.cia.canje-d.erpco.canje,ciaEfectivo:d.cia.efectivo,erpcoEfectivo:d.erpco.efectivo,difEfectivo:d.cia.efectivo-d.erpco.efectivo,ciaPrepago:d.cia.prepago,erpcoPrepago:d.erpco.prepago,difPrepago:d.cia.prepago-d.erpco.prepago,ciaTotal:ciaT,erpcoTotal:erpT,diferencia:ciaT-erpT,resultado:Math.abs(ciaT-erpT)<.01?'CUADRADO':ciaT>erpT?'MÁS EN CIA':'MÁS EN ERPCO'}}).sort((a,b)=>Math.abs(b.diferencia)-Math.abs(a.diferencia));
state.result={cia,erpco,avaSur,avaTrt,depCia,depErpco,diffs};renderSummary();setStatus('Conciliación procesada correctamente. Revisa los totales antes de descargar.','ok');$('#actions').classList.remove('hidden')}catch(e){console.error(e);setStatus(e.message||'No fue posible procesar los archivos.','error')}};
function renderSummary(){const r=state.result;let ciaTotal=0,erpTotal=0,difCanje=0;for(const b of Object.keys(r.cia.summary)){const c=r.cia.summary[b],e=r.erpco[b]||{};ciaTotal+=c.canje+c.efectivo+c.prepago;erpTotal+=(e.canje||0)+(e.efectivo||0)+(e.prepago||0);difCanje+=Math.abs(c.difCanje||0)}const warnings=[];for(const [k,l] of TYPES)if(!state.files.some(f=>detectType(f.name)?.key===k)&&!['cia','erpcoSur','erpcoSurVb','erpcoTrt','erpcoTrtVb'].includes(k))warnings.push(`${l}: no cargado (se tomará $0.00)`);const s=$('#summary');s.innerHTML=`<div class="kpi"><small>Total CIA (sin IVA)</small><strong>${money(ciaTotal)}</strong></div><div class="kpi"><small>Total ERPCO</small><strong>${money(erpTotal)}</strong></div><div class="kpi ${Math.abs(ciaTotal-erpTotal)<.01?'ok':'bad'}"><small>Diferencia global</small><strong>${money(ciaTotal-erpTotal)}</strong></div><div class="kpi"><small>Dif. Canje → Otros ingresos</small><strong>${money(difCanje)}</strong></div><div class="kpi"><small>AVA SUR / TRT</small><strong>${money(r.avaSur)} / ${money(r.avaTrt)}</strong></div><div class="kpi"><small>Depósitos ERPCO / CIA</small><strong>${money(r.depErpco)} / ${money(r.depCia)}</strong></div>${warnings.length?`<div class="warning-list"><b>Advertencias</b><ul>${warnings.map(x=>`<li>${x}</li>`).join('')}</ul></div>`:''}`;s.classList.remove('hidden')}
function writeCell(ws,addr,val){if(!ws[addr])ws[addr]={t:typeof val==='number'?'n':'s',v:val};else{ws[addr].v=val;ws[addr].t=typeof val==='number'?'n':'s';delete ws[addr].f}}
function buildDiffSheet(diffs){const data=[['REPORTE DE DIFERENCIAS CIA VS ERPCO'],['Generado',new Date().toLocaleString('es-MX')],[],['Conductor','Nombre','Marca','CIA Canje','ERPCO Canje','Dif. Canje','CIA Efectivo','ERPCO Efectivo','Dif. Efectivo','CIA Prepago','ERPCO Prepago','Dif. Prepago','Total CIA','Total ERPCO','Diferencia','Resultado'],...diffs.map(d=>[d.id,d.nombre,d.marca,d.ciaCanje,d.erpcoCanje,d.difCanje,d.ciaEfectivo,d.erpcoEfectivo,d.difEfectivo,d.ciaPrepago,d.erpcoPrepago,d.difPrepago,d.ciaTotal,d.erpcoTotal,d.diferencia,d.resultado])];const ws=XLSX.utils.aoa_to_sheet(data);ws['!cols']=[{wch:14},{wch:30},{wch:18},...Array(12).fill({wch:14}),{wch:18}];for(let r=5;r<=data.length;r++)for(const c of ['D','E','F','G','H','I','J','K','L','M','N','O'])if(ws[c+r])ws[c+r].z='$#,##0.00;[Red]-$#,##0.00';return ws}
$('#download').onclick=async()=>{try{const r=state.result;if(!r)return;const tpl=await fetch('assets/plantilla-masterweb.xlsx').then(x=>{if(!x.ok)throw new Error('No se pudo cargar la plantilla. Publica también la carpeta assets.');return x.arrayBuffer()});const wb=XLSX.read(tpl,{type:'array',cellStyles:true}),ws=wb.Sheets[wb.SheetNames[0]];const fecha=$('#fecha').value?new Date($('#fecha').value+'T12:00:00'):new Date();writeCell(ws,'D9',$('#recaudacion').value||'Villahermosa');writeCell(ws,'M9',fecha);ws['M9'].z='dd/mm/yyyy';const row={'SUR VOLKSBUS':14,'SUR':15,'TRT':16,'TRT VOLKSBUS':17};for(const [b,n] of Object.entries(row)){const c=r.cia.summary[b]||{},e=r.erpco[b]||{};writeCell(ws,'D'+n,c.canje||0);writeCell(ws,'E'+n,c.efectivo||0);writeCell(ws,'F'+n,c.prepago||0);writeCell(ws,'G'+n,e.canje||0);writeCell(ws,'H'+n,e.efectivo||0);writeCell(ws,'I'+n,e.prepago||0);writeCell(ws,'J'+n,(c.canje||0)-(e.canje||0));writeCell(ws,'K'+n,(c.efectivo||0)-(e.efectivo||0));writeCell(ws,'L'+n,(c.prepago||0)-(e.prepago||0))}
const ciaCanje=Object.values(r.cia.summary).reduce((a,x)=>a+x.canje,0),ciaEf=Object.values(r.cia.summary).reduce((a,x)=>a+x.efectivo,0),ciaPr=Object.values(r.cia.summary).reduce((a,x)=>a+x.prepago,0);const ivaCanje=Object.values(r.cia.summary).reduce((a,x)=>a+(x.ivaCanje||0),0);writeCell(ws,'D19',ciaCanje);writeCell(ws,'E19',ciaEf);writeCell(ws,'F19',ciaPr);writeCell(ws,'G19',Object.values(r.erpco).reduce((a,x)=>a+x.canje,0));writeCell(ws,'H19',Object.values(r.erpco).reduce((a,x)=>a+x.efectivo,0));writeCell(ws,'I19',Object.values(r.erpco).reduce((a,x)=>a+x.prepago,0));writeCell(ws,'J19',ciaCanje-Object.values(r.erpco).reduce((a,x)=>a+x.canje,0));writeCell(ws,'K19',ciaEf-Object.values(r.erpco).reduce((a,x)=>a+x.efectivo,0));writeCell(ws,'L19',ciaPr-Object.values(r.erpco).reduce((a,x)=>a+x.prepago,0));
// IVA y totales se obtienen de los totales CIA: el formato de origen reporta subtotal + IVA.
const ivaEf=Math.round((Object.values(r.cia.summary).reduce((a,x)=>a+(x.ivaEfectivo||0),0))*100)/100,ivaPr=Math.round((Object.values(r.cia.summary).reduce((a,x)=>a+(x.ivaPrepago||0),0))*100)/100;writeCell(ws,'D20',0);writeCell(ws,'E20',ivaEf);writeCell(ws,'F20',ivaPr);writeCell(ws,'D21',ciaCanje);writeCell(ws,'E21',ciaEf+ivaEf);writeCell(ws,'F21',ciaPr+ivaPr);writeCell(ws,'E26',ciaEf);writeCell(ws,'F26',ivaEf);writeCell(ws,'G26',ciaEf+ivaEf);writeCell(ws,'K26',ciaPr);writeCell(ws,'L26',ivaPr);writeCell(ws,'M26',ciaPr+ivaPr);writeCell(ws,'G32',ciaEf+ivaEf);writeCell(ws,'M32',ciaPr+ivaPr);writeCell(ws,'M36',r.avaSur);writeCell(ws,'M37',r.avaTrt);const difByBrand=b=>Math.abs(r.cia.summary[b]?.difCanje||0);writeCell(ws,'M38',difByBrand('SUR VOLKSBUS'));writeCell(ws,'M39',difByBrand('SUR'));writeCell(ws,'M40',difByBrand('TRT'));writeCell(ws,'M41',difByBrand('TRT VOLKSBUS'));writeCell(ws,'G38',r.depErpco);writeCell(ws,'G40',r.depCia);const otros=r.avaSur+r.avaTrt+difByBrand('SUR VOLKSBUS')+difByBrand('SUR')+difByBrand('TRT')+difByBrand('TRT VOLKSBUS');writeCell(ws,'M42',otros);writeCell(ws,'G42',r.depErpco-r.depCia);writeCell(ws,'L45',(ciaEf+ivaEf)+(r.depErpco-r.depCia)+otros);writeCell(ws,'C47',$('#observaciones').value||'');
const fichas=[...document.querySelectorAll('.ficha-row')].map(x=>({n:x.querySelector('.ficha-nombre').value.trim(),v:num(x.querySelector('.ficha-importe').value)})).filter(x=>x.n||x.v);for(let i=0;i<7;i++){writeCell(ws,'C'+(62+i),fichas[i]?.n||'');writeCell(ws,'D'+(62+i),fichas[i]?.v||0)}const totalF=fichas.reduce((a,x)=>a+x.v,0);writeCell(ws,'C69','Total');writeCell(ws,'D69',totalF);writeCell(ws,'L69','DIFERENCIA');writeCell(ws,'M69',totalF-((ciaEf+ivaEf)+(r.depErpco-r.depCia)+otros));
if(wb.SheetNames.includes('Diferencias CIA-ERPCO'))delete wb.Sheets['Diferencias CIA-ERPCO'];else wb.SheetNames.push('Diferencias CIA-ERPCO');wb.Sheets['Diferencias CIA-ERPCO']=buildDiffSheet(r.diffs);XLSX.writeFile(wb,`INTEGRACION MASTERWEB ${$('#fecha').value||'CONCILIACION'}.xlsx`,{cellStyles:true})}catch(e){setStatus(e.message,'error')}};
$('#csvDiff').onclick=()=>{if(!state.result)return;const ws=buildDiffSheet(state.result.diffs),csv=XLSX.utils.sheet_to_csv(ws),blob=new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='DIFERENCIAS_CIA_ERPCO.csv';a.click();URL.revokeObjectURL(a.href)};
